#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 1

#undef TAPPING_TERM
#define TAPPING_TERM 310

#define PERMISSIVE_HOLD

#define COMBO_TERM 37

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 15

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 9

#define SERIAL_NUMBER "erwYr/DzNoaE"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 16

#define MY_COMBO_COUNT 1

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

